// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"

void glue_sntp_on_time(uint64_t utc_time_in_milliseconds) {
  MG_INFO(("UTC time in milliseconds from SNTP: %llu, current time: %llu",
           utc_time_in_milliseconds, mg_now()));
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct adc_value s_adc_value = {0};
void glue_get_adc_value(struct adc_value *data) {
  *data = s_adc_value;  // Sync with your device
}
void glue_set_adc_value(struct adc_value *data) {
  s_adc_value = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct PWM s_PWM = {0};
void glue_get_PWM(struct PWM *data) {
  *data = s_PWM;  // Sync with your device
}
void glue_set_PWM(struct PWM *data) {
  s_PWM = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct leds s_leds = {false, false, false};
void glue_get_leds(struct leds *data) {
  *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
  s_leds = *data; // Sync with your device
}
